-- Fabric notebook source

-- METADATA ********************

-- META {
-- META   "kernel_info": {
-- META     "name": "sqldatawarehouse"
-- META   },
-- META   "dependencies": {
-- META     "warehouse": {
-- META       "default_warehouse": "67fbcfda-3717-adcf-48d4-ba74a63a0bd5",
-- META       "known_warehouses": [
-- META         {
-- META           "id": "67fbcfda-3717-adcf-48d4-ba74a63a0bd5",
-- META           "type": "Datawarehouse"
-- META         }
-- META       ]
-- META     }
-- META   }
-- META }

-- CELL ********************

-- ============================================================
-- NHL ANALYTICS - GOLD WAREHOUSE TABLE SETUP
-- ============================================================
--
-- Target Warehouse:
--   nhl_gold_warehouse
--
-- Source Schema:
--   PostgreSQL gold schema
--
-- Architecture:
--
--   Silver Natural Keys
--          ↓
--   Gold Natural Keys (nhl_*_id)
--          ↓
--   Gold Surrogate Keys (BIGINT IDENTITY)
--          ↓
--   Gold Fact Tables
--
-- Fabric Warehouse Requirements:
--
--   1. IDENTITY columns must use BIGINT.
--   2. Fabric Warehouse does NOT support specifying
--      IDENTITY seed or increment values.
--
--   Correct Fabric syntax:
--
--       BIGINT IDENTITY
--
--   NOT:
--
--       BIGINT IDENTITY(1,1)
--
-- ============================================================



-- ============================================================
-- DIM TEAM
-- ============================================================
--
-- team_id:
--   Gold surrogate key generated by Fabric Warehouse.
--
-- nhl_team_id:
--   NHL API natural/business key.
--
-- ============================================================

CREATE TABLE nhl_gold_warehouse.dbo.dim_team (

    -- Surrogate Key
    team_id BIGINT NOT NULL IDENTITY,

    -- NHL API Business Key
    nhl_team_id INT NOT NULL,

    -- Team Information
    place_name VARCHAR(100),
    team_name VARCHAR(100) NOT NULL,
    team_common_name VARCHAR(100),
    team_abbrev VARCHAR(10) NOT NULL,

    -- Organization
    conference_abbrev VARCHAR(10),
    conference_name VARCHAR(100),
    division_abbrev VARCHAR(10),
    division_name VARCHAR(100),

    -- Assets
    team_logo VARCHAR(1000),

    -- Audit
    created_at DATETIME2(6),
    updated_at DATETIME2(6)
);



-- ============================================================
-- DIM PLAYER
-- ============================================================
--
-- player_id:
--   Gold surrogate key generated by Fabric Warehouse.
--
-- nhl_player_id:
--   NHL API natural/business key.
--
-- draft_team_id:
--   Gold surrogate key referencing dim_team.team_id.
--
-- ============================================================

CREATE TABLE nhl_gold_warehouse.dbo.dim_player (

    -- Surrogate Key
    player_id BIGINT NOT NULL IDENTITY,

    -- NHL API Business Key
    nhl_player_id INT NOT NULL,

    -- Relationships
    draft_team_id BIGINT,

    -- Player Information
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    player_slug VARCHAR(255),

    -- Current Player Information
    is_active BIT,
    position VARCHAR(50),
    shoots_catches VARCHAR(10),

    -- Physical Attributes
    height_in_inches INT,
    height_in_centimeters INT,
    weight_in_pounds INT,
    weight_in_kilograms INT,

    -- Birth Information
    birth_date DATE,
    birth_city VARCHAR(100),
    birth_country VARCHAR(100),

    -- Draft Information
    draft_year INT,
    draft_round INT,
    draft_pick_in_round INT,
    draft_overall_pick INT,

    -- Honors
    in_top_100_all_time BIT,
    in_hhof BIT,

    -- Assets
    headshot VARCHAR(1000),
    hero_image VARCHAR(1000),

    -- Audit
    created_at DATETIME2(6),
    updated_at DATETIME2(6)
);



-- ============================================================
-- DIM DATE
-- ============================================================
--
-- date_id:
--   Deterministic date key.
--
-- Example:
--   September 3, 2026 = 20260903
--
-- This is NOT an identity column.
--
-- ============================================================

CREATE TABLE nhl_gold_warehouse.dbo.dim_date (

    -- Date Key
    date_id INT NOT NULL,

    -- Date
    full_date DATE NOT NULL,

    -- Day
    day_of_month INT,
    day_name VARCHAR(20),
    day_of_week INT,

    -- Week
    week_of_year INT,

    -- Month
    month_number INT,
    month_name VARCHAR(20),

    -- Quarter
    quarter INT,

    -- Year
    year INT,

    -- Weekend Indicator
    is_weekend BIT,

    -- Audit
    created_at DATETIME2(6),
    updated_at DATETIME2(6)
);



-- ============================================================
-- DIM GAME
-- ============================================================
--
-- game_id:
--   Gold surrogate key generated by Fabric Warehouse.
--
-- nhl_game_id:
--   NHL API natural/business key.
--
-- date_id:
--   Gold date dimension key.
--
-- away_team_id / home_team_id:
--   Gold dim_team surrogate keys.
--
-- ============================================================

CREATE TABLE nhl_gold_warehouse.dbo.dim_game (

    -- Surrogate Key
    game_id BIGINT NOT NULL IDENTITY,

    -- NHL API Business Key
    nhl_game_id INT NOT NULL,

    -- Date Relationship
    date_id INT NOT NULL,

    -- Game Context
    season_id INT NOT NULL,
    game_type_id INT NOT NULL,
    game_date DATE,
    start_time_utc DATETIME2(6),

    -- Team Relationships
    away_team_id BIGINT NOT NULL,
    home_team_id BIGINT NOT NULL,

    -- Game Results
    away_team_score INT,
    home_team_score INT,
    away_shots_on_goal INT,
    home_shots_on_goal INT,

    -- Venue
    venue VARCHAR(255),
    venue_time_zone VARCHAR(100),

    -- Audit
    created_at DATETIME2(6),
    updated_at DATETIME2(6)
);



-- ============================================================
-- FACT TEAM STANDINGS
-- ============================================================
--
-- team_standings_id:
--   Gold surrogate fact key.
--
-- team_id:
--   Gold dim_team surrogate key.
--
-- date_id:
--   Gold dim_date key.
--
-- ============================================================

CREATE TABLE nhl_gold_warehouse.dbo.fact_team_standings (

    -- Surrogate Key
    team_standings_id BIGINT NOT NULL IDENTITY,

    -- Dimension Keys
    team_id BIGINT,
    date_id INT NOT NULL,

    -- Context
    season_id INT,
    game_type_id INT,

    -- Overall Record
    games_played INT,
    wins INT,
    losses INT,
    ot_losses INT,
    ties INT,
    points INT,
    point_pctg DECIMAL(8,6),
    win_pctg DECIMAL(8,6),
    regulation_wins INT,
    regulation_win_pctg DECIMAL(8,6),
    regulation_plus_ot_wins INT,
    regulation_plus_ot_win_pctg DECIMAL(8,6),
    shootout_wins INT,
    shootout_losses INT,

    -- Goals
    goals_for INT,
    goals_against INT,
    goal_differential INT,
    goals_for_pctg DECIMAL(8,6),
    goal_differential_pctg DECIMAL(8,6),

    -- Home Record
    home_games_played INT,
    home_wins INT,
    home_losses INT,
    home_ot_losses INT,
    home_ties INT,
    home_points INT,
    home_goals_for INT,
    home_goals_against INT,
    home_goal_differential INT,
    home_regulation_wins INT,
    home_regulation_plus_ot_wins INT,

    -- Road Record
    road_games_played INT,
    road_wins INT,
    road_losses INT,
    road_ot_losses INT,
    road_ties INT,
    road_points INT,
    road_goals_for INT,
    road_goals_against INT,
    road_goal_differential INT,
    road_regulation_wins INT,
    road_regulation_plus_ot_wins INT,

    -- Last 10 Games
    l10_games_played INT,
    l10_wins INT,
    l10_losses INT,
    l10_ot_losses INT,
    l10_ties INT,
    l10_points INT,
    l10_goals_for INT,
    l10_goals_against INT,
    l10_goal_differential INT,
    l10_regulation_wins INT,
    l10_regulation_plus_ot_wins INT,

    -- Rankings
    league_sequence INT,
    league_home_sequence INT,
    league_road_sequence INT,
    league_l10_sequence INT,
    conference_sequence INT,
    conference_home_sequence INT,
    conference_road_sequence INT,
    conference_l10_sequence INT,
    division_sequence INT,
    division_home_sequence INT,
    division_road_sequence INT,
    division_l10_sequence INT,
    wildcard_sequence INT,
    waivers_sequence INT,

    -- Streak
    streak_code VARCHAR(20),
    streak_count INT,

    -- Audit
    created_at DATETIME2(6),
    updated_at DATETIME2(6)
);



-- ============================================================
-- FACT ROSTERS
-- ============================================================
--
-- roster_id:
--   Gold surrogate fact key.
--
-- team_id:
--   Gold dim_team surrogate key.
--
-- player_id:
--   Gold dim_player surrogate key.
--
-- date_id:
--   Gold dim_date key.
--
-- ============================================================

CREATE TABLE nhl_gold_warehouse.dbo.fact_rosters (

    -- Surrogate Key
    roster_id BIGINT NOT NULL IDENTITY,

    -- Dimension Keys
    team_id BIGINT,
    player_id BIGINT,
    date_id INT NOT NULL,

    -- Effective Dating
    effective_from DATETIME2(6) NOT NULL,
    effective_to DATETIME2(6),

    -- Roster Information
    sweater_number INT,

    -- Audit
    created_at DATETIME2(6),
    updated_at DATETIME2(6)
);



-- ============================================================
-- FACT PLAYER GAME STATS
-- ============================================================
--
-- player_stats_id:
--   Gold surrogate fact key.
--
-- player_id:
--   Gold dim_player surrogate key.
--
-- game_id:
--   Gold dim_game surrogate key.
--
-- date_id:
--   Gold dim_date key.
--
-- ============================================================

CREATE TABLE nhl_gold_warehouse.dbo.fact_player_game_stats (

    -- Surrogate Key
    player_stats_id BIGINT NOT NULL IDENTITY,

    -- Dimension Keys
    player_id BIGINT,
    game_id BIGINT,
    date_id INT NOT NULL,

    -- Scoring
    goals INT,
    assists INT,
    points INT,
    game_winning_goals INT,
    overtime_goals INT,

    -- Special Teams
    power_play_goals INT,
    power_play_points INT,
    shorthanded_goals INT,
    shorthanded_points INT,

    -- Other Statistics
    shots INT,
    plus_minus INT,
    shifts INT,
    pim INT,
    time_on_ice VARCHAR(20),

    -- Audit
    created_at DATETIME2(6),
    updated_at DATETIME2(6)
);



-- ============================================================
-- VERIFICATION - GOLD WAREHOUSE TABLES
-- ============================================================

SELECT
    'nhl_gold_warehouse' AS warehouse_name,
    s.name AS schema_name,
    t.name AS table_name
FROM nhl_gold_warehouse.sys.tables t
INNER JOIN nhl_gold_warehouse.sys.schemas s
    ON t.schema_id = s.schema_id
WHERE s.name = 'dbo'
  AND t.name IN (
      'dim_team',
      'dim_player',
      'dim_date',
      'dim_game',
      'fact_rosters',
      'fact_team_standings',
      'fact_player_game_stats'
  )
ORDER BY
    warehouse_name,
    table_name;



-- ============================================================
-- COLUMN VERIFICATION
-- ============================================================

SELECT
    t.name AS table_name,
    c.column_id,
    c.name AS column_name,
    TYPE_NAME(c.user_type_id) AS data_type,
    c.max_length,
    c.is_nullable,
    c.is_identity
FROM nhl_gold_warehouse.sys.tables t
INNER JOIN nhl_gold_warehouse.sys.columns c
    ON t.object_id = c.object_id
INNER JOIN nhl_gold_warehouse.sys.schemas s
    ON t.schema_id = s.schema_id
WHERE s.name = 'dbo'
  AND t.name IN (
      'dim_team',
      'dim_player',
      'dim_date',
      'dim_game',
      'fact_rosters',
      'fact_team_standings',
      'fact_player_game_stats'
  )
ORDER BY
    t.name,
    c.column_id;

-- METADATA ********************

-- META {
-- META   "language": "sql",
-- META   "language_group": "sqldatawarehouse"
-- META }
